### ISSUE TITLE
Admin/PII code review feedback

### ISSUE THREAD

**Issue by mguy-usgs** [kbiegel-usgs/EQIL_metadata#3]
1. nice readme.d
2. for the listed dependencies, can you provide any applicable version numbers here too?
3. please also add the disclaimer text to the python code file itself as a comment because sometimes after downloaded the python code file is separated from the rest of the files in the repository...
4. happy to see example input and output files
5. strongly recommend that you put in some try/except blocks for error handling especially around things like file manipulation (e.g. lines 237-240, 368-370, 413-417,...) as these are an easy area to encounter errors, but consider in other areas too
6. Noticed general contact info for ghsc metadata manager/contact and for science base as well, I think this is all OK and completely public information, just making sure you agree with that.
7. line 94, the default citation info is very specific, confirming you are comfortable with this as the default? and OK as public, maybe fine because the corresponding metadata lives on sciencebase and thus is public, just making sure this makes sense as a default. OK as this is preliminary code, but may want to consider as part of a formal version release a configuration file that has defaults, and then an example config file can be in public repository, and  center/scientist/project specific config files can be in a internal repository
9. relative to line 73 and 94 looking at python coding standards there is a line length limit for readability https://www.python.org/dev/peps/pep-0008/#id19 consider indentations in these long lists as described https://www.python.org/dev/peps/pep-0008/#indentation

**Comment by kbiegel-usgs** [comment]
All changes were made.
